import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main>
					<div className="h-20 px-10 flex justify-between items-center bg-slate-300">
						<Link href="/" className="font-semibold">
							Logo
						</Link>
						<Link
							href="/login"
							className="p-2 bg-sky-400 text-slate-100 rounded-lg"
						>
							Login
						</Link>
					</div>
					{children}
				</main>
			</body>
		</html>
	);
}
